spring:
  application:
    name: myWork
  datasource:
      url: jdbc:mysql://120.79.91.4:3306/mywork?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 120.79.91.4
    port: 6379
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
      timeout: 0
  data:
    mongodb:
      uri: mongodb://120.79.91.4:27017/mydb
  cloud:
    stream:
      binders:
        test:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 10.0.20.132
                port: 5672
                username: root
                password: root
                virtual-host: /unicode-pay
  bindings:
    testOutPut:
      destination: testRabbit
      content-type: application/json
      default-binder: test

server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mapper/*.xml
